import "./globals.css";
import NavBar from "../components/NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "use-shopping-cart";

// TODO ADD GOOD METDATA
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <CartProvider
            currency="INR"
            shouldPersist
            cartMode="checkout-session"
            stripe={process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY}
          >
            <Toaster />
            <NavBar />
            <div className="flex justify-center ">{children}</div>
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
