import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import { ClerkProvider } from "@clerk/nextjs";

// TODO CHANGE FONT
const inter = Inter({ subsets: ["latin"] });

// TODO ADD GOOD METDATA
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavBar />
          <div className="flex justify-center bg-slate-500 items-center p-24">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
